### ISSUE TITLE
Possibility of saving a slave without necessity of having a mount point

### ISSUE THREAD

**Issue by arvanus** [labbsr0x/docker-dns-bind9#7]
Hi, I'm preparing a new remove slave server, and would like to run inside a cluster without a fixed volume, it would be very useful to have the possibility os passing my servers/domains list as an environment variable parameter, and in the startup the container would create the required `named.conf.default-zones` file
The docker-compose would be something like this (suggestions are welcome)

```
version: '3.5'

services:
  bind9:
    restart: unless-stopped
    image: labbsr0x/dns-bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
            MASTER_DOMAINS: 192.168.1.1:domain1.com,192.168.3.1:domain2.com
```

The startup script would then create the required file

If you agree, I could do this change and pull a patch

Thanks
